authors/urls.py
from . import views
from django.urls import path

from rest_framework.routers import SimpleRouter

rest_framework_router = SimpleRouter()
rest_framework_router.register(
    'api',
    viewset=views.AuthorsAPIViewSet,
    basename='authors-api'
)

app_name = 'authors'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/create/', views.login_create, name='login_create'),
    path('register/create/', views.register_create, name='register_create'),
    # Flake8: noqa
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/recipe/create/',
         views.DashboardRecipeCreate.as_view(), name='recipe_create'),
    path('dashboard/recipe/delete/',
         views.DashboardRecipeDelete.as_view(), name='recipe_delete'),
    path('dashboard/recipe/<int:id>/update/',
         views.DashboardRecipeEdit.as_view(), name='recipe_edit'),
    path('profile/<int:id>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update/',
         views.ProfileUpdateView.as_view(), name='profile_update'),
]

urlpatterns += rest_framework_router.urls

recipes/urls.py
from . import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

recipes_api_router = SimpleRouter()
recipes_api_router.register(
    '',
    views.RecipesAPIViewSet,
    basename='recipes-api'
)

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipesHomeView.as_view(), name='home'),
    path(
        'recipes/search/',
        views.RecipesSearchView.as_view(),
        name='search'
    ),
    path(
        'recipes/tags/<slug:slug>/',
        views.RecipesTagView.as_view(),
        name='search_tag'
    ),
    path(
        'recipes/category/<int:id>/',
        views.RecipesCategoryView.as_view(),
        name='category'
    ),
    path(
        'recipes/<int:pk>/',
        views.RecipeDetailView.as_view(),
        name='detail'
    ),
    path(
        'recipes/api/v1/<int:pk>/',
        views.RecipeDetailApiView.as_view(),
        name='detail_api'
    ),
    path(
        'recipes/api/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair'
    ),
    path(
        'recipes/api/token/verify/',
        TokenVerifyView.as_view(),
        name='token_verify'
    ),
    path(
        'recipes/api/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    path(
        'recipes/api/',
        include(recipes_api_router.urls)
    ),
    path(
        'recipes/tags/api/<int:pk>/',
        views.tags_api_detail,
        name='tags_api_detail'
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/views.py
import os

from .models import Recipe
from utils.pagination import make_pagination
from tag.models import Tag

from django.shortcuts import get_list_or_404
from django.http import Http404, JsonResponse
from django.db.models import Q
from django.forms.models import model_to_dict
from django.views.generic import ListView, DetailView
from django.utils.translation import get_language
from django.utils.translation import gettext as _

RECIPES_PER_PAGE = int(os.environ.get('RECIPES_PER_PAGE', 6))
PAGES_TO_DISPLAY = int(os.environ.get('PAGES_TO_DISPLAY', 4))


class RecipesListView(ListView):
    model = Recipe
    context_object_name = 'recipes'
    template_name = 'recipes/pages/home.html'
    ordering = ['-id']

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )
        qs = qs.select_related('user', 'category')
        qs = qs.prefetch_related('user__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        pagination = make_pagination(
            request=self.request,
            obj_list=ctx['recipes'],
            obj_per_page=RECIPES_PER_PAGE,
            pages_to_display=PAGES_TO_DISPLAY
        )
        ctx.update({
            'recipes': pagination['page'],
            'pagination_range': pagination['page_range'],
            'search_bar': True,
            'translation': get_language(),
        })
        return ctx


class RecipeApiListView(RecipesListView):
    def render_to_response(self, context, **response_kwargs):
        queryset = self.get_context_data().get('recipes')
        recipes = list(queryset.object_list.values())
        return JsonResponse(recipes, safe=False)


class RecipesHomeView(RecipesListView):
    template_name = 'recipes/pages/home.html'


class RecipesCategoryView(RecipesListView):
    template_name = 'recipes/pages/categoryView.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = get_list_or_404(
            qs,
            category__id=self.kwargs.get('id'))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')
        ctx.update({
            'title': f'{ctx.get("recipes")[0].category.name} - '
            f'{category_translation} | ',
        })
        return ctx


class RecipesSearchView(RecipesListView):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        if not search_term:
            raise Http404()
        qs = qs.filter(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        ctx.update({
            'additional_query': f'&q={search_term}',
            'search_term': search_term
        })
        return ctx


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipeView.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )
        qs = qs.select_related('user')
        qs = qs.prefetch_related('tags')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_view': True,
            'title': f'{ctx.get("recipe").title} | ',
            'search_bar': False,
            'translation': get_language()
        })
        return ctx


class RecipeDetailApiView(RecipeDetailView):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data().get('recipe')
        recipe_dict = model_to_dict(recipe)
        if recipe_dict['cover']:
            recipe_dict['cover'] = self.request.build_absolute_uri('/') + \
                recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''
        del ([
            recipe_dict['is_published'],
            recipe_dict['preparation_steps_is_html']
        ])
        recipe_dict.update({
            'user': recipe.user.username,
            'created_at': str(recipe.created_at),
            'updated_at': str(recipe.updated_at),
        })
        return JsonResponse(
            recipe_dict,
            safe=False
        )


class RecipesTagView(RecipesListView):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        slug = self.kwargs.get('slug', '')
        qs = qs.filter(
            tags__slug=slug
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        slug = self.kwargs.get('slug', '')
        tag_title = Tag.objects.filter(
            slug=slug
        ).first()
        if not tag_title:
            tag_title = 'No recipes found'
        ctx.update({
            'title': tag_title,
        })
        return ctx

recipes/views/api.py
from recipes.models import Recipe
from recipes.serializers import RecipeSerializer
from recipes.permissions import IsOwner
from tag.serializers import TagSerializer
from tag.models import Tag

from rest_framework import status
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.pagination import PageNumberPagination

from django.shortcuts import get_object_or_404


class RecipesAPIPagination(PageNumberPagination):
    page_size = 5


class RecipesAPIViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = RecipesAPIPagination
    permission_classes = [IsAuthenticatedOrReadOnly]
    http_method_names = ['get', 'head', 'options', 'patch', 'post', 'delete']

    def get_queryset(self):
        qs = super().get_queryset()
        category_id = self.request.query_params.get('category_id', '')
        if category_id and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)
        return qs

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=request.user)
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
        )

    def get_object(self):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk
        )
        self.check_object_permissions(self.request, obj)
        return obj

    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner()]
        return super().get_permissions()

    def partial_update(self, req, *args, **kwargs):
        recipe = self.get_object()
        serializer = RecipeSerializer(
            instance=recipe,
            many=False,
            data=self.request.data,
            context={'request': self.request},
            partial=True
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            data=serializer.data
        )


@ api_view()
def tags_api_detail(req, pk):
    tag = Tag.objects.filter(pk=pk).first()
    if not tag:
        return Response({
            'error_message': 'Tag not found.'
        }, status=status.HTTP_404_NOT_FOUND)
    serializer = TagSerializer(instance=tag, many=False)
    return Response(serializer.data)

recipes/views/web.py
from ..models import Recipe
from utils.pagination import make_pagination
from tag.models import Tag

from django.conf import settings
from django.shortcuts import get_list_or_404
from django.http import Http404, JsonResponse
from django.db.models import Q
from django.forms.models import model_to_dict
from django.views.generic import ListView, DetailView
from django.utils.translation import get_language
from django.utils.translation import gettext as _


class RecipesListView(ListView):
    model = Recipe
    context_object_name = 'recipes'
    template_name = 'recipes/pages/home.html'
    ordering = ['-id']

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )
        qs = qs.select_related('user', 'category')
        qs = qs.prefetch_related('user__profile')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        pagination = make_pagination(
            request=self.request,
            obj_list=ctx['recipes'],
            obj_per_page=settings.RECIPES_PER_PAGE,
            pages_to_display=settings.PAGES_TO_DISPLAY
        )
        ctx.update({
            'recipes': pagination['page'],
            'pagination_range': pagination['page_range'],
            'search_bar': True,
            'translation': get_language(),
        })
        return ctx


class RecipesHomeView(RecipesListView):
    template_name = 'recipes/pages/home.html'


class RecipesCategoryView(RecipesListView):
    template_name = 'recipes/pages/categoryView.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = get_list_or_404(
            qs,
            category__id=self.kwargs.get('id'))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')
        ctx.update({
            'title': f'{ctx.get("recipes")[0].category.name} - '
            f'{category_translation} | ',
        })
        return ctx


class RecipesSearchView(RecipesListView):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        if not search_term:
            raise Http404()
        qs = qs.filter(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        ctx.update({
            'additional_query': f'&q={search_term}',
            'search_term': search_term
        })
        return ctx


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipeView.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )
        qs = qs.select_related('user')
        qs = qs.prefetch_related('tags')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_view': True,
            'title': f'{ctx.get("recipe").title} | ',
            'search_bar': False,
            'translation': get_language()
        })
        return ctx


class RecipeDetailApiView(RecipeDetailView):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data().get('recipe')
        recipe_dict = model_to_dict(recipe)
        if recipe_dict['cover']:
            recipe_dict['cover'] = self.request.build_absolute_uri('/') + \
                recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''
        del ([
            recipe_dict['is_published'],
            recipe_dict['preparation_steps_is_html']
        ])
        recipe_dict.update({
            'user': recipe.user.username,
            'created_at': str(recipe.created_at),
            'updated_at': str(recipe.updated_at),
        })
        return JsonResponse(
            recipe_dict,
            safe=False
        )


class RecipesTagView(RecipesListView):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        slug = self.kwargs.get('slug', '')
        qs = qs.filter(
            tags__slug=slug
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        slug = self.kwargs.get('slug', '')
        tag_title = Tag.objects.filter(
            slug=slug
        ).first()
        if not tag_title:
            tag_title = 'No recipes found'
        ctx.update({
            'title': tag_title,
        })
        return ctx

recipes/templates/recipes/partials/head.html
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css"
        integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css"
        integrity="sha512-W/zrbCncQnky/EzL+/AYwTtosvrM+YG/V6piQLSe2HuKS6cmbw89kjYkp3tWFn1dkWV7L1ruvJyKbLz73Vlgfg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css"
        integrity="sha512-P9pgMgcSNlLb4Z2WAB2sH5KBKGnBfyJnq+bhcfLCFusrRc4XdXrhfDluBl/usq75NF5gTDIMcwI1GaG5gju+Mw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        
    {% load static %}
    <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'global/default.css' %}">

recipes/templates/recipes/partials/recipe.html
{% load i18n %}

<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{{recipe.get_absolute_url}}">
            {% if recipe.cover %}
                <img src="{{recipe.cover.url}}" alt="Alternative">
            {% else %}
                <img src="https://placehold.co/1080x720" alt="Placeholder">
            {% endif %}
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{{recipe.get_absolute_url}}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>
    <div class="recipe-author-container">
        {% if recipe.user is not None %}
            <span class="recipe-author-item">
                {% if recipe.user.profile %}
                    <a href="{% url "authors:profile" recipe.user.profile.id %}">
                {% endif %}
                <i class="fas fa-user"></i>
                {% if recipe.user.first_name %}
                    <span>{{recipe.user.first_name}}</span>
                    {% if recipe.user.last_name %}
                        <span>{{recipe.user.last_name}}</span>
                    {% endif %}
                {% else %}
                    <span>{{recipe.user}}</span>
                {% endif %}
                {% if recipe.user.profile %}
                    </a>
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i> {{recipe.created_at|date:"d/m/Y H:i:s"}}
        </span>
        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name|capfirst}}</span>
            </a>
        </span>
        {% endif %}
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <i class="fas fa-stopwatch"></i>
                <span>{% translate 'Preparation' %}</span>                       
            </h3>
            <div class="recipe-meta-text">
                <span>{{recipe.preparation_time}}</span>
                <span>{% translate recipe.preparation_time_unit %}</span>
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <i class="fas fa-pizza-slice"></i>
                <span>{% translate 'Servings' %}</span>
            </h3>
            <div class="recipe-meta-text">
                <span>{{recipe.servings}}</span>
                <span>{% translate recipe.servings_unit %}</span>
            </div>
        </div>
    </div>
    {% if is_detail_view is not True %}
    <div class="recipe-footer">
        <a href="{{recipe.get_absolute_url}}" class="recipe-read-more button button-dark button-full-width">
            <i class="fas fa-eye"></i>
            <span>{% translate 'read more' %}...</span>
        </a>
    </div>
    {% endif %}

    {% if is_detail_view %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html %}
                {{recipe.preparation_steps|safe}}
            {% else %}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}
        </div>
        {% if recipe.tags.all %}
        <div class="tags-container-list">
            <h3>Tags:</h3>
            <div class="tags-list">
                {% for tag in recipe.tags.all %}
                    <a class="tags-list-item" href="{% url "recipes:search_tag" tag.slug %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    {% endif %}
</div>